### ISSUE TITLE
[Bug]: Awakened Draconium Dust recipe missing

### ISSUE THREAD

**Issue by Pillgar** [AllTheMods/atm9nf#116]
### Possible Fixes

Yes

### Modpack Version

1.15

### What happened?

The recipe for Awakened Draconium Dust is missing since the addition of the Draconium Evolution mod.  This was fixed about a month ago for atm9 - skies: https://github.com/AllTheMods/All-the-mods-9-Sky/issues/385

I think this was the code added to kubejs:

```
    event.custom({
        type: 'thermal:pulverizer',
        ingredients: [
            Ingredient.of('draconicevolution:awakened_draconium_ingot').toJson()
        ],
        results: [
            Item.of('draconicevolution:awakened_draconium_dust')
        ],
        processingTime: 100
    })

})
```

**Comment by slowthgt** [comment]
Can confirm the issue, adding the custom event from https://github.com/AllTheMods/All-the-mods-9-Sky/blob/dev/kubejs/server_scripts/mods/thermal/recipes.js minus the first 3 event calls does allow you to get it from a pulverizer.
