### ISSUE TITLE
[Bug]: no suspicious clay spawning 

### ISSUE THREAD

**Issue by CaveManOBO** [AllTheMods/atm9nf#119]
### Possible Fixes

No

### Modpack Version

atm9 no frills 0.1.13

### What happened?

when you go to the ancient city to find sus clay you think you would find some. i have been to 4 ancient city's and nothing. there are empty blocks near the basalt usually where sus clay would spawn but not a single one in 4 locations

**Comment by CaveManOBO** [comment]
if i downloaded the latest version but my world wasn't saved in the latest version if that's a thing where i can transfer my world to the new version that would be nice

**Comment by Hibanan** [comment]
I also ran into this on my server. But brushing non sus clay would sometimes provide the template. Same with sus soul sand
