### ISSUE TITLE
[Bug]: Missing quest background images due to missing quest pics folders missing in the assets folder

### ISSUE THREAD

**Issue by ianwijma** [AllTheMods/atm9nf#124]
### Possible Fixes

Yes

### Modpack Version

0.1.16

### What happened?

There are no quest background pictures due to folders missing in `packmenu/resources/assets/atm/textures/questpics` missing directories:

![2024-08-18_11 21 36](https://github.com/user-attachments/assets/2e435b39-7b36-4c3f-94b5-8816b179852c)

Downloaded the latest version from CurseForge and the zip seems to miss them as well:

![image](https://github.com/user-attachments/assets/7a8e59b1-91bd-4a4f-aeca-f360fa308ca5)

**Comment by TheBedrockMaster** [comment]
They're there for me.

**Comment by ianwijma** [comment]
Indeed, thevortex is already aware of it, just wanted to make sure it's trackable. 

Downloading the folders from GitHub into that folder fixes the issue. :D 

![2024-08-18_11 45 02](https://github.com/user-attachments/assets/908f5748-8c3b-488a-b73f-27f41b2c6e8d)

**Comment by TheBedrockMaster** [comment]
You will still notice 2 broken quests, one in Apothosis and one in Basic Storage, I just made a PR that fixes those 2.
