### ISSUE TITLE
[Improvement Proposal] Creation of an Attainable Endgame ATM Star x9 Block

### ISSUE THREAD

**Issue by servperso** [AllTheMods/atm9nf#127]
Hi everyone,

Today, while playing with some friends, we did some math regarding the endgame "ATM Star x9" block. We realized that it's practically unattainable without either breaking the server or playing for multiple years. So, I made a few tweaks to the quest book and created an alternate recipe for the ATM Star. This new recipe becomes achievable once you unlock the ATM Bee (the actual final quest).

I'm sharing this idea with the community now. It’s not a finished product, but rather a starting point for rebalancing the endgame, making the ATM Star Block x9 more attainable. :)

The objective is purely about farming. It requires scaling up factories and farming bees, which adds a bit more longevity to the game.

PS: Apologies if this isn't the right place to post. Just let me know if it needs to be moved!

![new_atm_receipe](https://github.com/user-attachments/assets/5d32ed4a-b12a-4b17-9446-9d4fe1d21fc3)
![creative_objective](https://github.com/user-attachments/assets/7ec6ea96-ad03-4ebc-8bc3-bd053531f8b1)

```
{
    "type": "minecraft:crafting_shaped",
    "pattern": [
        "#R#",
        "JBS",
        "#A#"
    ],
    "key": {
        "#": {
            "item": "allthetweaks:atm_star_shard"
        },
        "J": {
            "item": "allthemodium:unobtainium_block"
        },
        "B": {
            "item": "allthetweaks:patrick_star"
        },
        "S": {
            "item": "allthemodium:allthemodium_block"
        },
        "A": {
            "item": "minecraft:diamond_block"
        },
        "R": {
            "item": "allthetweaks:nether_star_block"
        }
    },
    "result": {
        "item": "allthetweaks:atm_star",
        "count": 1
    }
}
```

**Comment by TheBedrockMaster** [comment]
Cool idea, however the 9x Star Block isn't meant to obtained, it is possible though without cheating.
