### ISSUE TITLE
[Quests issues]: Extreme Reactors quest descriptions.

### ISSUE THREAD

**Issue by HarshaCA** [AllTheMods/atm9nf#130]
### Modpack Version

0.1.16

### Describe the issue

Good day, peeps!

So I have seen that in the **Extreme reactors quests** the descriptions are broken.

Seems to be some kind of dependency issue, since the quests only show some **strings that contain "gregtech**" in the name.
Might have been caused by some kind of copy-paste from ATM9 quest description.

Images for reference:
![image](https://github.com/user-attachments/assets/1e165a54-b8a4-4004-9292-51f3a65111ad)

![image](https://github.com/user-attachments/assets/d8586e7a-158c-4084-a6f1-89300294653f)

If you need more information on the topic, let me know.
Have a nice day!

**Comment by TheBedrockMaster** [comment]
Do you know how long the quests have been like that? As in which version they broke.

**Comment by HarshaCA** [comment]
I am sorry, but I have no idea from which version this problem occured.

I only played this version with some friends on a private server.

In rest, I played ATM9, not ATM9NF.

**Comment by TheBedrockMaster** [comment]
I figured it out before you sent this but thanks, I'll get this fixes soon™️
