### ISSUE TITLE
issues introduced by the change to occultism pentacles

### ISSUE THREAD

**Issue by Elendol** [AllTheMods/atm9nf#19]
Hi,

First of I want to say I really like the changes to Occultism. It has never that easy and fun to use this mod, coupled with the stargate mod for easy book and quill books, easy craft of empty books. The new multiblock is very useful and really improve the gameplay. Thank you for that.

I noticed 2 issues though:

- the updated pentacles are correctly displayed in the book but the game crashes once I click on the eye to try to see the layout in world.
- if you update the aviar pentacle before summoning the sapling trader the beaver familiar ritual overrides it (I tried with the 4 different saplings required for the sapling trader, the pentacle sees 4 saplings also matching the beaver ritual)

**Comment by Kevin-Marsh** [comment]
The issue with the crash on rendering the ritual is actually an unrelated issue. It is caused by the interaction of occultism with shaders causing the crash and occurs in the base mod. I will have to modify the conflicting recipes that you brought up.
