### ISSUE TITLE
Dupe Bug

### ISSUE THREAD

**Issue by jasonk9** [AllTheMods/atm9nf#31]
When using either crafting on a stick or a normal crafting table it is possible to duplicate items.

For example when making torches I was able to duplicate infinite coal and sticks simply by clicking continually on the output.

NOTE: I have seen this same bug in the full ATM9 pack also.

I can upload a video later if that helps to track it down.

**Comment by Mitchell5200** [comment]
should be fixed in v0.1.16, released 2 days ago, please update and confirm
