### ISSUE TITLE
AE2 Drives power usage v0.1.7

### ISSUE THREAD

**Issue by BoereworsG** [AllTheMods/atm9nf#32]
I just updated my server from 0.0.8 to 0.1.7.
My AE2 storage system was offline, after troubleshooting to make sure no p2p cables overlap and that nothing went wrong with my controllers i found the issue is the ME Drives. vanilla AE2 or the extended Drives, when i disconnect the system boots up. i then went and added cables between each drive to see if its maybe a certain cell, its all of them. When looking at the power usage its using 3 million per drive, which is really nothing since my generation is 24 Nitro reactors. 
The issue is after the update the power usage increased substantially, and no matter how many power acceptors and flux points i add, this does not fix it. 

Is there a limit on how much power can run through an AE2 power acceptor? if this is the case, how can we increase it?
or is there a file i can change to get the power to what it was? a config i can copy over from 0.0.8?

**Comment by Kevin-Marsh** [comment]
The power of an AE system is limited by the amount of power that can be stored in the system. Add some AE energy cells to your network to increase throughput.

**Comment by Kevin-Marsh** [comment]
This was also caused by megacells. The newer versions should have this fixed.
