### ISSUE TITLE
crafting table quest

### ISSUE THREAD

**Issue by Jacob-Suldaan** [AllTheMods/atm9nf#33]
The crafting table quest is now to make a filter but the description still says to make a crafting table in your inventory 2x2 crafting area. This also makes that quest unable to be completed, making progression (through that quest line) impossible.

**Comment by santoizag** [comment]
same problem no solucion yet

**Comment by whatthedrunk** [comment]
Thanks this will be fixed in the next update https://github.com/AllTheMods/atm9nf/commit/c00d7b5416d1acce492dc736f346196a6ceb8fc1
