### ISSUE TITLE
[0.1.7] Broken quests in chapter 2

### ISSUE THREAD

**Issue by LuciusV** [AllTheMods/atm9nf#34]
Quest "Pieces of the Ender Dragon" in chapter 2 is broken because of not-existing item "ends_delight:dragon_tooth"

**Comment by whatthedrunk** [comment]
thanks for the notes! this will be fixed in the next version.

**Comment by whatthedrunk** [comment]
https://github.com/AllTheMods/atm9nf/commit/3630d5efb673ad81e04a1ec403e3b5b3f80b85ef
