### ISSUE TITLE
Applied Energistics 2 - Color Applicator quest not completing

### ISSUE THREAD

**Issue by rrawk** [AllTheMods/atm9nf#46]
Like the title says, the color applicator quest doesn't switch to complete. 

![image](https://github.com/AllTheMods/atm9nf/assets/153854116/cbd829d2-5258-43e9-a6ff-6dd0d74a6a51)

**Comment by TheBedrockMaster** [comment]
Add quest bug label.

**Comment by TheBedrockMaster** [comment]
Looks to be a bug with FTB Quests, you'll probably need to go into editing mode and force complete it.
