### ISSUE TITLE
Ad Astra - Preparing Some Oxygen wont progress

### ISSUE THREAD

**Issue by rrawk** [AllTheMods/atm9nf#47]
![image](https://github.com/AllTheMods/atm9nf/assets/153854116/1987526b-a6aa-406e-ac83-2229e42aefc2)

**Comment by Kaden-Warner** [comment]
Can confirm this is happening to me as well on the latest version of ATM9 NF

**Comment by MunchyG** [comment]
i am have the same issue, is there a way to force it to progress with commands for now

**Comment by Kaden-Warner** [comment]
I found a fix for it in the main ATM 9 pack's GitHub, I put in a pull request to merge that fix over to No Frills
https://github.com/AllTheMods/atm9nf/pull/54
