### ISSUE TITLE
[Bug]: Productive Bees Mod Needs Updating

### ISSUE THREAD

**Issue by MunchyG** [AllTheMods/atm9nf#49]
### Possible Fixes

Yes

### Modpack Version

No Frills 0.1.8

### What happened?

Productive Bees has a crash loop bug, that has been patched in newer versions of the mod but ATM is still using the old version

### Developer reports

https://github.com/JDKDigital/productive-bees/issues/479

**Comment by Kevin-Marsh** [comment]
This should be fixed in the latest version.
