### ISSUE TITLE
[Bug]: huge fps drops with shaders and create

### ISSUE THREAD

**Issue by Speedygunyke** [AllTheMods/atm9nf#50]
### Possible Fixes

Yes

### Modpack Version

0.1.8

### What happened?

the create mod has an eternal shaderpack called Flywheel but this is automaticly disabled if using regular shaders   and causes huge fps drops that make it unplayable   this can be fixed by adding a small compat mod called Iris & Oculus Flywheel Compat
( https://www.curseforge.com/minecraft/mc-mods/iris-flywheel-compat )

**Comment by whatthedrunk** [comment]
added to All the Mods 9 - No Frills-0.1.11 which should be approved any min thanks
