### ISSUE TITLE
Updated server to most recent version. Apotheosis mage gems blood staff EDIT( after some research iron spellbooks has changed staff)

### ISSUE THREAD

**Issue by jayboi117** [AllTheMods/atm9nf#52]
After updating our server to the most recent version we have noticed that the Apotheosis mage gems have become error gems and The Blood Staff from irons spells and spell books can no longer use spells. Is this a intended change or a bug on our server after the update?

**Comment by Kevin-Marsh** [comment]
This should hopefully be resolved with the latest update.
