### ISSUE TITLE
FTB Quests blank - 0.1.13

### ISSUE THREAD

**Issue by Trepez** [AllTheMods/atm9nf#64]
As the title describes. After updating server and pack to 0.1.13 the ftb quests have gone blank with only the background appearing.
![BlankQuests](https://github.com/AllTheMods/atm9nf/assets/165763437/47bf913f-3c7d-4d0f-8221-48e7e6289973)

**Comment by Kevin-Marsh** [comment]
I would guess that you haven't copied the configs file properly since quests are stored in there. Please try recopying the appropriate files and let us know if it works.

**Comment by Zascal96** [comment]
i have the same problem on my server. This happened to me for the first time, previous updates haven't had these issues. I updated via g-portal. The questbook isn't even available in newly generated singleplayer worlds.

any suggestions other than the one you posted?

**Comment by Kevin-Marsh** [comment]
Can you go open /config/ftbquests/quests/chapters and tell me if there is anything in that folder?

**Comment by Trepez** [comment]
> Can you go open /config/ftbquests/quests/chapters and tell me if there is anything in that folder?

Both my modpacks folder and the servers config folder both have a list of .snbt files. 
One thing I did find, was my atm9nf modpack version of 0.1.8 has an additional 4 .snbt files.
Could these be the progress that is missing? Don't want to add/move files if it may corrupt something.
![ftbquestfiles](https://github.com/AllTheMods/atm9nf/assets/165763437/a9324e8e-39d3-4a47-b08c-f8d107d1acbb)

**Comment by xenonmb** [comment]
same problem on a fresh install

**Comment by xenonmb** [comment]
I checked the server files and it seems the server install has no ftbquests folder at all. GPortal Server, fresh Install 0.1.13.

![Screenshot_2024-04-04_01-59-Rat](https://github.com/AllTheMods/atm9nf/assets/21304246/b9db40fb-111a-4ab5-8c53-036f231ae16f)

**Comment by Kevin-Marsh** [comment]
> same problem on a fresh install

You definitely have a corrupted server install.

**Comment by xenonmb** [comment]
> > same problem on a fresh install
> 
> You definitely have a corrupted server install. Trepez I am not so sure of.

i copied the ftbquests folder from the pack to the server and it seems to work fine, only weird that it was missing from the automatic install

**Comment by Trepez** [comment]
> > > same problem on a fresh install
> > 
> > 
> > You definitely have a corrupted server install. Trepez I am not so sure of.
> 
> i copied the ftbquests folder from the pack to the server and it seems to work fine, only weird that it was missing from the automatic install

So copying ftbquest files from your pack to the server folder resolved this for you?

**Comment by xenonmb** [comment]
> > > > same problem on a fresh install
> > > 
> > > 
> > > You definitely have a corrupted server install. Trepez I am not so sure of.
> > 
> > 
> > i copied the ftbquests folder from the pack to the server and it seems to work fine, only weird that it was missing from the automatic install
> 
> So copying ftbquest files from your pack to the server folder resolved this for you? I only ask cause there are 3 of us on our server and I don't believe my pack would contain my friends quest progress in its files.

yes, I downloaded the server pack from curseforge, and copied the ftbquests folder over to the server where it was missing. There were 4 people on the server at the time with empty quests. For the quest progress in case of an update like on your side, I think this is stored not in config/ftbquests but world/ftbquests, Mind you, all of that is on the SERVER side, just pointing that out cause the screenshot you shared seems to be from a client install.
