### ISSUE TITLE
[0.1.13] Server pack does not work on windows: missing file

### ISSUE THREAD

**Issue by LuciusV** [AllTheMods/atm9nf#65]
startserver.bat
Error: could not open `libraries/net/minecraftforge/forge/1.20.1-47.2.21/win_args.txt'
Restarting automatically in 10 seconds (press Ctrl + C to cancel)

I remember that startserver.bat was able to install forge automatically in earlier versions, is it possible to restore this fucntionality?

**Comment by xenonmb** [comment]
It still DOES download and install forge if needed. Maybe your path is somehow invalid or too long?
