### ISSUE TITLE
Quest Book spelling error

### ISSUE THREAD

**Issue by ItsHesus** [AllTheMods/atm9nf#67]
In the Apotheosis Enchanting section of the quest book, every instance of "Retification" is a mispelling of the actual word "Rectification"

**Comment by TheBedrockMaster** [comment]
This appears to have since been fixed :)

**Comment by TheBedrockMaster** [comment]
I think this fix is coming in the next update (not sure though).

**Comment by TheBedrockMaster** [comment]
Should now be fixed :)
