### ISSUE TITLE
server config not working

### ISSUE THREAD

**Issue by EduardoPais** [AllTheMods/atm9nf#68]
I have started a multiplayer server using the provided server pack and it's been great however I wanted to enable the flux network chunkloading so as ussual I went to the config folder and set the chunk loading to true but I still doesnt work I have tried to change other configs as enabling flight in twilight and the same issue has occured, If someone knows what I am doing wrong I'd appreciate it.

**Comment by Kevin-Marsh** [comment]
Are you ensuring that the server isn't running when you are editing configs?

**Comment by EduardoPais** [comment]
Yes I have changed it when the server was not runnig I also tried the reload command and its still not working
