### ISSUE TITLE
Server hosting server issue

### ISSUE THREAD

**Issue by JakeTheSnake1253** [AllTheMods/atm9nf#70]
Hi, 
So I have been trying to make a server for my friends and I to use but I am getting this error when I have attempted to connect to the server from my computer. 
"Internal exception: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJasonException: Use JsonReader.setLenient(true) to accept malformed json at line 1 column 1 path $" 

When my friends try to connect they just timeout.

**Comment by SSSenge** [comment]
I had the same issue, it turned out that the version of the modpack I was using was mismatched with the server. Updating my version fixed it for me.
