### ISSUE TITLE
Invisible Chunks,

### ISSUE THREAD

**Issue by GCbird08** [AllTheMods/atm9nf#71]
My game only loads 28 by 28 chunks in the overworld and in other dimensions only 1, the chunks are still interactable but completely invisible, I've tried multiple things like increasing memory and changing visual settings.  No luck so far, the entire modpack works I'm just sort of trapped in a cube.

**Comment by Jmpp2909** [comment]
reduce render distance to like 10 and restart the game if you didnt yet, seems like a render thread crash, i see people having the game default to 64 chunks of render
