### ISSUE TITLE
Awkward point of death.

### ISSUE THREAD

**Issue by Logidroid** [AllTheMods/atm9nf#72]
hello this is really very annoying how to remove this, or to have only the last death ?

![image](https://github.com/AllTheMods/atm9nf/assets/58258858/329d2ecf-ea2b-4385-beeb-2bfa8f1d4066)

**Comment by EduardoPais** [comment]
If u press "J" and go to options then "Waypoints" u can disable "Create Deathpoints" and in "Waypoint Beacons" u can enable "Auto Remove Death Waypoints".
