### ISSUE TITLE
[v 0.0.4] buried treasure map broken

### ISSUE THREAD

**Issue by Schrimpes** [AllTheMods/atm9nf#8]
The buried treasure map from a shipwreck appears in the inventory like a normal map. It also behaves like a normal one, i.e. right-clicking creates a map of the current position.

![2024-01-11_00 58 13](https://github.com/AllTheMods/atm9nf/assets/93662041/971b0a9a-7bc0-41c1-85d1-887dff364498)
![2024-01-11_01 13 54](https://github.com/AllTheMods/atm9nf/assets/93662041/fa9a714b-c1d1-4593-905b-bcfd1277278f)
![2024-01-11_01 14 19](https://github.com/AllTheMods/atm9nf/assets/93662041/688eee60-f38b-4a7b-b123-7cab5e9f30af)

was tested with several maps from several shipwrecks

**Comment by whatthedrunk** [comment]
should be fixed now and if it breaks again let supplementaries  know as they keep breaking it
