### ISSUE TITLE
Armor trim quest

### ISSUE THREAD

**Issue by Kripton-081** [AllTheMods/atm9nf#82]
I dont think the armor trim quest is working?

I have spent a considerable time collecting the trims to the point where i collected one of each but i still havent been rewarded/achieve the reward?
![atm9 trims](https://github.com/AllTheMods/atm9nf/assets/171142011/a52bca3d-6b07-413d-b74a-797407be03b5)

**Comment by Kripton-081** [comment]
![trims](https://github.com/AllTheMods/atm9nf/assets/171142011/3e5cea82-cb6a-4fcf-8dd5-88f4571237ff)

**Comment by TheBedrockMaster** [comment]
Add quest bug label.

**Comment by TheBedrockMaster** [comment]
Looks to be a bug with FTB Quests, you'll probably need to go into editing mode and force complete it.
