### ISSUE TITLE
[Bug]: Anvil Drop Enchantment Transfer Not Working

### ISSUE THREAD

**Issue by starter3xd** [AllTheMods/atm9nf#91]
### Possible Fixes

Yes

### Modpack Version

0.1.14

### What happened?

When dropping an anvil on an enchanted item and a book, nothing happens. The expected behavior is that the enchantment from the enchanted item should be transferred to the book.

**Comment by TheBedrockMaster** [comment]
This feature is not in No Frills :(

**Comment by starter3xd** [comment]
> This feature is not in No Frills :(

Where you got this info?

**Comment by TheBedrockMaster** [comment]
The discord and in Youtube videos

**Comment by Nyxane** [comment]
Check if SFM is in the pack, if not then whomp whomp
