### ISSUE TITLE
[Bug]: Refined Storage

### ISSUE THREAD

**Issue by clyons2009** [AllTheMods/atm9nf#98]
### Possible Fixes

Yes

### Modpack Version

1.14

### What happened?

My refined stoarge system doesnt show any of my items anymore i tried to see if anything was disconnected and tried breaking everything and repalcing it again. I also tried leaving and joining back, But nothings working

**Comment by clyons2009** [comment]
![image](https://github.com/AllTheMods/atm9nf/assets/173410238/d7eeaef6-c1fe-47db-894d-caaa68914fba)

**Comment by clyons2009** [comment]
it also still lets me use the item inside to craft things
But i cant see any items inside

**Comment by clyons2009** [comment]
My stuff showed for a second when i was changing the display

**Comment by TheBedrockMaster** [comment]
Has it started working since or are the items gone?
